services:
    postgres:
        image: postgres:16-alpine
        container_name: pokemon-db
        environment:
            POSTGRES_DB: pokemon_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - '5434:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 10s
            timeout: 5s
            retries: 3
volumes:
    postgres_data:
